### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by Krishnakumarshrestha** [JacekPardyak/resume#4]
i got this error 
Error in namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,  : 
  lazy-load database '/cloud/lib/x86_64-pc-linux-gnu-library/4.2/fastmap/R/fastmap.rdb' is corrupt
In addition: Warning message:
In namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,  :
  internal error -3 in R_decompress1

**Comment by JacekPardyak** [comment]
Probably you should update your installed R packages. `fastmap` is used by `testthat` not directly by the `resume` package.
